# Generated by Django 4.2.8 on 2023-12-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytodo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="added_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
